<?php

class SP_SimpleSlider_Model_Slider extends Mage_Core_Model_Abstract
{
   protected function _construct()
   {
       $this->_init('sp_simpleslider/slider');
   }

   public function save()
   {
       return parent::save(); // TODO: Change the autogenerated stub
   }
}
