<?php

class SP_SimpleSlider_Model_Resource_Slider
    extends Mage_Core_Model_Resource_Db_Abstract
{
    /** {@inheritdoc} */
    protected function _construct()
    {
        $this->_init('sp_simpleslider/slider', 'slider_id');
    }

    public function save(Mage_Core_Model_Abstract $object)
    {
        return parent::save($object); // TODO: Change the autogenerated stub
    }
}